### ISSUE TITLE
Blurry Image Preview

### ISSUE THREAD

**Issue by frankyyy02** [IndieGoodies/PastePal#11]
**Describe the bug**
Images/screenshots viewed on the sidebar are blurry.

**To Reproduce**
1. Take a screenshot - in my case with CleanshotX
2. Pop open the sidebar
3. Press space on screenshot to preview
4. Blurry image

**Expected behavior**
Image should be shown in a clear state.

**Screenshots**
Attached.

**Desktop (please complete the following information):**
 - OS: macOS Ventura

**Additional context**
Here is a screenshot of the Preview shows when pressing 'Space' on an image in the sidebar/bottombar.

<img width="772" alt="CleanShot 2023-07-05 at 13 47 42@2x" src="https://github.com/onmyway133/PastePal/assets/96891477/5f72bd38-6ca5-48ba-a442-4478d38f315a">

**Comment by frankyyy02** [comment]
Hi
Wondering if any updates on this? This appears to be an issue still so wondering if any insight?
Wondering it this might be a cause of https://github.com/IndieGoodies/PastePal/issues/33?
Thanks

**Comment by onmyway133** [comment]
@frankyyy02 for now CleanShotX is saving the captured image as a file, and PastePal only previews a small quick look version of it, I will improve this
