### ISSUE TITLE
auto focus on first item is lost when navigating between collections

### ISSUE THREAD

**Issue by OOOytun** [IndieGoodies/PastePal#19]
**Describe the bug**
when i am navigating between collections (with shortcuts: `cmd + ]` or ` cmd + [ ` or with clicking to collection) focus on first item is lost in some collections so i can't paste or navigate between items to paste from side window.

**To Reproduce**
1. Go to side window
2. Click on collections
3. See focused item ready for paste

**Expected behavior**
while i am navigating between collections first item should always be focused, so i can paste or choose between what i want to paste.

**Screenshots**
![image](https://github.com/onmyway133/PastePal/assets/90776671/823b300f-8ad4-46eb-8d7e-f1b0cec52ce2)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 
 - Version: 14.0

**Comment by onmyway133** [comment]
@OOOytun Hi, this should be solved in recent latest versions of PastePal

**Comment by OOOytun** [comment]
@onmyway133 yeah it is solved. Thank you!
