### ISSUE TITLE
First time Install / Run Set Up GUI/ Tutorial

### ISSUE THREAD

**Issue by sdanielracing** [IndieGoodies/PastePal#26]
**Is your feature request related to a problem? Please describe.**
Although it is a -decently-  easy app to use, it would make it easier to use for the first time you run it a Step by step GUI that made you:

-Choose where you want the clipboard bar to be situated. (Right, Left, Top, Bottom)
-How to activate it (select shortcut etc)
-Quick GUI Tutorial on how to: 
      --Add to Collection
      --Use the quick selection (CMD + Number).
      --Edit title, text from saved items.
      --How to request new feautures.

To be honest, it took me a while to figure this things out and I beleivbe it would be a somewhat easy to do fix for you. Plus it would be a great way to gain advantage on your competitors.

I have some more ideas for your product to become the best of the best. but I beleive I have already spammed you enought for today.

Feel free to PM me if you're interested to talk.

Thank you.

**Comment by onmyway133** [comment]
@sdanielracing I've been working on detailing features in this documentation https://docs.indiegoodies.com/pastepal, hope it can give some more information about common PastePal features.
