### ISSUE TITLE
Allow disabling "multi select" in quick mode

### ISSUE THREAD

**Issue by submarines-and** [IndieGoodies/PastePal#27]
**Describe the solution you'd like**
Hello, just bought the app and like it so far, but I have one request. My shortcut to show the sidebar is "cmd+shift+v". If I use this to toggle quick mode and hold the modifiers down, I get stuck in multi select mode when using the arrows to navigate between clips.

My request is a toggle to disable multi select. That way, I could keep my keybinding and only paste one item.

**Describe alternatives you've considered**
I have considered switching keybinding, but I have many years of muscle memory assigned to this one, so if at all possible I would like to keep it.

**Comment by onmyway133** [comment]
@submarines-and Hi, for now with Quick Mode, you can use a single shortcut to open side window, cycle through the list of items and release to copy/paste https://docs.indiegoodies.com/pastepal/Mac/features/quick-mode

By "hold the modifiers down", you mean the down arrow key?

**Comment by submarines-and** [comment]
Modifier = shift key, which is part of my sidebar shortcut, but also activates selecting multiple clips.

However, since posting this, I have instead learned to stop holding the keys down like I used to In my old app and now instead press them once and confirm with space, as is intended, so I will close this!
