### ISSUE TITLE
add export option for collections; save as txt or csv

### ISSUE THREAD

**Issue by jawadakhan97** [IndieGoodies/PastePal#29]
**Is your feature request related to a problem? Please describe.**
i cannot easily export my collections as text to save somewhere, i need to manually copy paste them and then put them manually into categories i recreate in a yaml file which correspond to the names of the collections

**Describe the solution you'd like**
where the backup/sync option is, a button which says 'Save as..." or "Export" which could export the collections in a plaintext txt, csv, or yaml format so i can keep the collections archived, i use pastepal, have premium, and use it A LOT, this would help keep my important quick ref info and stuff secure somewhere else in addition to the cloud sync

**Describe alternatives you've considered**
manually copy pasting, screenshotting and then using OCR

**Additional context**

**Comment by onmyway133** [comment]
@javentous Hi, can you check the Export feature https://docs.indiegoodies.com/pastepal/Mac/features/export to see if it fits your need?

**Comment by jawadakhan97** [comment]
> @javentous Hi, can you check the Export feature https://docs.indiegoodies.com/pastepal/Mac/features/export to see if it fits your need?

hi, thanks! i've unfortunately transitioned to a linux machine and manually copied over my collections... feel free to close this issue, thanks for the work!
