### ISSUE TITLE
Pasted item goes back to the start of the queue

### ISSUE THREAD

**Issue by pietz** [IndieGoodies/PastePal#30]
I would find it way more helpful if pasted items from the past, go back to the start of the queue. Or at least there should be an option for that. Think about it. If I paste something old, chances are I might need it another time again.

**Comment by onmyway133** [comment]
@pietz thanks for the suggestion, for now can you try these "Focus recent clip" that will move the recently copied/pasted clip to the top?

<img width="461" alt="image" src="https://github.com/IndieGoodies/PastePal/assets/2284279/edb5db4b-c231-473a-b2bc-17216d3096e4">
