### ISSUE TITLE
Upgrade button not working

### ISSUE THREAD

**Issue by sk1ter** [IndieGoodies/PastePal#32]
**Describe the bug**
Unlock premium button not working

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Upgrade' button
3. From modal window click 'Unlock Premium' button
4. Button does nothing

**Expected behavior**
Allow to upgrade (start purchasing process)

**Screenshots**
https://streamable.com/sewh5r

**Desktop (please complete the following information):**
 - OS: MacOS Sonama 14.3 
 - App version: Latest from app store

**Comment by onmyway133** [comment]
@sk1ter hi, thanks for reaching out. Can you post screenshot again, https://streamable.com/sewh5r returns not found for now

**Comment by WillFulmer** [comment]
Related? MacOS Settings is greyed out and non functional:
<img width="241" alt="image" src="https://github.com/IndieGoodies/PastePal/assets/36053224/57224d9e-73a6-4be1-9870-b8b2a69b14fa">

...But it does work in the bottom left pane:
<img width="738" alt="image" src="https://github.com/IndieGoodies/PastePal/assets/36053224/e90c976c-d755-4734-82e0-4d6474c46a3f">

**Comment by onmyway133** [comment]
@WillFulmer in latest versions of PastePal, Settings menu work again now. You can also press Cmd+comma to open settings
