### ISSUE TITLE
Image Text Recognition Not Working

### ISSUE THREAD

**Issue by frankyyy02** [IndieGoodies/PastePal#33]
**Describe the bug**
Text recognition on images does not appear to work.

**To Reproduce**

1. Take screenshot
2. Copy to clipboard
3. Wait some time for recognition to process - minutes (tried up to days)
4. Search in PastePal on macOS
5. No results

**Expected behavior**
Results should be returned with search keywords

**Desktop (please complete the following information):**
 - 14.2.1 (23C71)
 - Latest from AppStore (24)

![CleanShot 2024-02-02 at 08 42 59@2x](https://github.com/IndieGoodies/PastePal/assets/96891477/8ea0c2e3-3ade-493e-9001-c2f8e55bb724)

![CleanShot 2024-02-02 at 08 44 15@2x](https://github.com/IndieGoodies/PastePal/assets/96891477/8eb405bc-f2a2-4b1c-9982-4e96f9552ee2)

**Comment by onmyway133** [comment]
Hi, thanks for letting me know. Have you enabled Recognize text in image option https://docs.indiegoodies.com/pastepal/Mac/features/recognize-text-image ?

**Comment by frankyyy02** [comment]
Yes, I do. 
When I do an export it’s empty. 
Recently rebuilt my Mac and same issue after fresh install.
Happy to review logs but haven’t found any from a brief look. Would be great to get this working. It’s one of the only reasons I still use Raycast.

Thanks

**Comment by onmyway133** [comment]
@frankyyy02 hi, you can preview (shift+space) to view plain text of the copied image, if text recognition works it will appear there.

**Comment by frankyyyyyyy** [comment]
Thanks for the response.
I have done some more digging, and I think this is an issue limited to CleanshotX's copy.

When taking a screenshot and hitting the copy button on the popup in Cleanshot, it appears as the below.  When doing the same with Shottr, the image text is OCRd.

![CleanShot 2024-05-07 at 07 29 53](https://github.com/IndieGoodies/PastePal/assets/30813767/6404ec4c-1412-4cbd-aa70-9dc051e65b3e)

**Comment by onmyway133** [comment]
@frankyyyyyyy you're right, for CleanShotX it saves as a file, not image data. For now PastePal only OCR image data content
