### ISSUE TITLE
Select all (CMD+a) in Main Window and the ability to select multiple items on iOS

### ISSUE THREAD

**Issue by ww7** [IndieGoodies/PastePal#40]
Select all (CMD+a) in Main Window is missing.

Selecting of multiple clipboard items planned on iOS?

**Comment by onmyway133** [comment]
@ww7 Hi, since items on main window is shown in page, even when we cmd+a to select all, it will select all items in the current page only. Added to backlog and I will try to support this

Regarding multiple selection on iPhone and iPad, that is not planned for now
