### ISSUE TITLE
URL cannot be pasted

### ISSUE THREAD

**Issue by HernandoR** [IndieGoodies/PastePal#43]
**Describe the bug**
the full url is copied and can seen in the history, but nothing is pasted

**To Reproduce**
1. open any website
2. copy the link(full url)
3. paste in any where else

**Expected behavior**
either full url is pasted, or only the main part( host and path) is pasted

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser: Any
 - Version: Any

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by onmyway133** [comment]
@HernandoR hi, thanks for reaching out

To trigger paste with PastePal, you can press Enter or double clicking on the clip
