### ISSUE TITLE
Rearrange clips after reusing them

### ISSUE THREAD

**Issue by gmrizzo** [IndieGoodies/PastePal#56]
**Is your feature request related to a problem? Please describe.**
When copying a clip that is not the first in the list the clip stays in the order that it previously was.

**Describe the solution you'd like**
When copying a clip that is not the first in the history, I would like to rearrange the clip to be the first again.

**Describe alternatives you've considered**
There is none

**Additional context**
It's the default behaviour that the "Paste" App has.
Is there a setting that I am missing?

**Comment by onmyway133** [comment]
@gmrizzo hi, thanks for reaching out. In PastePal settings you can configure to move recent copied clip to the top
Fore more information about PastePal you can view here https://docs.indiegoodies.com/pastepal

**Comment by gmrizzo** [comment]
Thanks for your fast response. I couldn't find a setting that provides the described behaviour. I'm on version 2.15.6 (171) and I can only find the "Queue" settings regarding any order but from the documentation this isn't what I was searching for.
![grafik](https://github.com/IndieGoodies/PastePal/assets/15858721/674a2f20-bffc-47ba-b4a8-ad4ae456ea79)

To clarify:
I'm copying two texts "A Text" and "B Text". The history shows 1. "B Text" and 2. "A Text". For example on "Maccy"-App, after selecting the second item in history "A Text", it's rearranging the items and shoes following order in history 1. "A Text" and 2. "B Text" as the first item is more recent in the clipboard history.

**Comment by onmyway133** [comment]
@gmrizzo Hi, it is called "Focus recent clip" in PastePal settings

**Comment by gmrizzo** [comment]
Thank you very much for your answer. I overlooked this option the whole time.
