### ISSUE TITLE
history inaccesble beyond page 14

### ISSUE THREAD

**Issue by everythingness** [IndieGoodies/PastePal#57]
hello i am about to press the purchase button but is this a bug?

i have a question about ‘history’ : in the preferences i have ‘keep history’ set to ‘forever’ and it looks like pastepal is keeping them all but i can only access pages 1-14 (and page 14 is shown as ‘1’) and there is no page 15 or higher at all.

![SCR-20240620-irxg](https://github.com/IndieGoodies/PastePal/assets/89503536/fe6ae49b-32cf-44b2-9e22-b58776246f28)

so how do i access the older clipboards?

but thanks for making a great piece of software!

**Comment by onmyway133** [comment]
@everythingness Hi thanks for reaching out. You can just scroll (or shift+ mouse scroll) to scroll through the page number

**Comment by ustupid1** [comment]
oh wow omg ok thanks ;) ha ha

**Comment by onmyway133** [comment]
@ustupid1 glad it works for you. I will close this issue, feel free to contact if you have any questions
