### ISSUE TITLE
PastePal Displays Copied Content as Scalet

### ISSUE THREAD

**Issue by petrbui** [IndieGoodies/PastePal#58]
**Describe the bug**
As shown in the screenshot, I can only see a small portion of the content I copied. I tried reinstalling the application, deleting the history, etc., but the issue persists.

**To Reproduce**
I purchased and installed the application.

**Expected behavior**
I expect to see the entire item that I copied.

**Screenshots**
![obrazek](https://github.com/IndieGoodies/PastePal/assets/32798156/9cd23ea1-5ba6-42d3-bfe1-e5f9f9dfa55d)
<img width="1255" alt="obrazek" src="https://github.com/IndieGoodies/PastePal/assets/32798156/275e78aa-0fa6-4050-adcb-ac69ffd28eec">

**Desktop (please complete the following information):**
 - OS: Sonoma 14.4.1

**Comment by petrbui** [comment]
sorry it was my fault https://docs.indiegoodies.com/pastepal/Mac/features/redact

**Comment by onmyway133** [comment]
@petrbui glad you sorted it out 👍
