### ISSUE TITLE
cant sync mac standalone premium user with iphone app.

### ISSUE THREAD

**Issue by UzerX1** [IndieGoodies/PastePal#60]
ive got a key from appsumo and i downloaded the standalone app for mac from the website and i activated the key, i downloaded the app in the app store for iphone and there was no option for activating premium from key or mac, i tried to download mac store version of app and there was no option for keys, could u help me?

**Comment by onmyway133** [comment]
@UzerX1 Hi, as stated on AppSumo "This freebie is for the standalone version of PastePal for Mac only"
