### ISSUE TITLE
PastePal is not ignoring input from Figma app

### ISSUE THREAD

**Issue by milos5593** [IndieGoodies/PastePal#73]
**Describe the bug**
Application is not ignoring input from Figma app even though I place it under ignore list. I have to pause the PastePal app in order to be able to copy paste in Figma.

**To Reproduce**
1. Install Figma desktop app for Mac
2. Click on settings
3. Add Figma app to ignore list

**Expected behavior**
I can use copy and paste functionality in Figma without interference from PastePal.

**Desktop (please complete the following information):**
 - OS: macOS 14.5 (23F79)
 - Apple M1 Pro
 - Figma App for Mac
 - Version 2.16.0 (175)

**Comment by onmyway133** [comment]
@milos5593 Hi thanks for reaching out. Do you have any apps under Allow list in PastePal?

**Comment by milos5593** [comment]
No, only under ignore where I added Figam to ignore list.


<img width="1452" alt="Screenshot 2024-08-14 at 22 37 24" src="https://github.com/user-attachments/assets/ec991f91-983c-4981-ab0e-9a962523944a">

<img width="1466" alt="Screenshot 2024-08-14 at 22 28 36" src="https://github.com/user-attachments/assets/6ee5da39-d4f4-4697-8a20-e1eff4913c64">

**Comment by onmyway133** [comment]
@milos5593 Hi, can you try latest release today to see if it works for you?

**Comment by milos5593** [comment]
Yup, now it works! Thanks for the quick fix.

**Comment by onmyway133** [comment]
@milos5593 Glad it works, I will close the issue for now
