### ISSUE TITLE
Search in side window ignores first characters

### ISSUE THREAD

**Issue by SimonMayerhofer** [IndieGoodies/PastePal#79]
**Describe the bug**
When opening the side window, I'm able to just start typing to use the search. Almost all of the times at least the first character is ignored. So if I type "test" the character in the search only show "est". Sometimes even more characters are ignored. 

**To Reproduce**
1. Open the sidewindow
2. type something like e.g. "test"
3. Be annoyed that the first charcters are ignored

**Expected behavior**
All typed characters are used for the search.

**Desktop (please complete the following information):**
 - OS: macOS 14.5 (23F79)

**Comment by onmyway133** [comment]
@SimonMayerhofer hi thanks for reaching out. This is a known issue, I'm working on improving this. Initially the idea is that the first character triggers search, it was not designed to immediately type right after that

**Comment by SimonMayerhofer** [comment]
Seems like this was fixed in one of the last updates. Thanks!
