### ISSUE TITLE
Some Preview popups in PastePal's Dark appearance are rendered unreadable

### ISSUE THREAD

**Issue by wjfeeney** [IndieGoodies/PastePal#87]
MacOS 15.0
PastePal v 2.16.4 (177)

Using Quick Look in PastePal's Dark mode, the Preview popup of clips taken from some Mac applications renders as black text on a dark background, and the text is too difficult to read. I think the popup in Dark mode should in all cases clearly show white text on a dark background.

By comparison, in PastePal's Light mode, the popup is always clear and readable (black text on white background).

Outside of PastePal, Quick Look renders either as black text on white background or white text on black background, and in all cases is clear and readable, so I don't think this is a Mac issue.

**Comment by onmyway133** [comment]
@wjfeeney Hi, thanks for letting me know. I will check this

**Comment by onmyway133** [comment]
This should be fixed in 2.16.6

**Comment by wjfeeney** [comment]
@onmyway133  Thank you!

**Comment by onmyway133** [comment]
@wjfeeney I will close this for now, feel free to open issue if you have any questions
