### ISSUE TITLE
gear settings icon initially missing in new clip

### ISSUE THREAD

**Issue by wjfeeney** [IndieGoodies/PastePal#89]
A new clip copied into PastePal, which appears in the side window as well as the main window, does not initially show the settings gear icon in the bottom right corner of the clip. I have to click in an older clip first, and then return to the new clip to see and access the gear icon. Having easy access to the settings in each clip is a useful feature, so I hope you will fix this issue.

**Comment by onmyway133** [comment]
@wjfeeney Hi thanks for the feedback, I'm aware of the issue. I will check and improve it

**Comment by wjfeeney** [comment]
@onmyway133 Thanks!

**Comment by onmyway133** [comment]
@wjfeeney This should be fixed in the latest version. Please try it and see if it's working for you, thanks

**Comment by wjfeeney** [comment]
Thank you! Your fix works.

**Comment by onmyway133** [comment]
@wjfeeney Glad to hear. I will close this for now, feel free to contact me if you need
