### ISSUE TITLE
App Won't Launch

### ISSUE THREAD

**Issue by MisShenanigans** [IndieGoodies/PastePal#93]
**Describe the bug**
So I am trying to use PastePal for Mac OS but the app just won't launch regardless of rebooting or reinstalling. 

**To Reproduce**
1. Download the app from Mac OS App Store
2. Click PastePal
3. Nothing happens
4. Click PastePal app again
5. Nothing happens
6. Repeat step 3

**Expected behavior**
I would expect the app to launch once I click on it. 

**Desktop (please complete the following information):**
 - Device: M2 MacBook Air 
 - OS: macOS Sequoia 15.1
 - Version: PastePal 2.16.7

**Additional context**
I also tried the standalone version but the app also refuse to launch that way.

**Comment by onmyway133** [comment]
@MisShenanigans Hi, thanks for the feedback. I see you close the issue, how does it go?
