### ISSUE TITLE
Can't hide menu bar icon 

### ISSUE THREAD

**Issue by garanda21** [IndieGoodies/PastePal#95]
**Describe the bug**
Not possible to hide menu bar icon, every time you uncheck the option to **"Show in status menu bar"**, after one second the option enables by it self. 

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Show in status menu bar' option
3. Wait couple of seconds

**Expected behavior**
Hide icon and keep option as desired

**Screenshots**
Video showing the behavior (Take a look at the icon on the menu bar after uncheck option):

https://github.com/user-attachments/assets/70d909fe-2308-4b7f-9de4-44527a349fb2

**Desktop (please complete the following information):**
 - OS: 15.1 (24B83)
 - Browser N/A
 - Version Pastepal: 2.16.7 (185)

**Comment by onmyway133** [comment]
@garanda21 Hi, thanks for reaching out. We need a way to trigger the side window, otherwise it would appear not showing to users. So we need to have defined a keyboard shortcut for "Toggle side window" first to be able to trigger the side window, then we can toggle off the status menu icon

**Comment by garanda21** [comment]
> @garanda21 Hi, thanks for reaching out. We need a way to trigger the side window, otherwise it would appear not showing to users. So we need to have defined a keyboard shortcut for "Toggle side window" first to be able to trigger the side window, then we can toggle off the status menu icon

Thanks for your reply, indeed that workaround works, that's enough for me, please feel free to close the issue.

**Comment by onmyway133** [comment]
@garanda21 Thanks for the follow up. glad it works for you.
