### ISSUE TITLE
History not clearing itself after a day

### ISSUE THREAD

**Issue by Chelayel** [IndieGoodies/PastePal#99]
1. Have history to auto clear after 1 day
<img width="270" alt="image" src="https://github.com/user-attachments/assets/0e7938a8-7158-4004-a0cd-a93495ab7eb0">

3. History of items more than 1 day are still shown
<img width="286" alt="image" src="https://github.com/user-attachments/assets/f0dec848-ddc2-4d6b-9ef7-79b5de06f234">

Maos version 15.1.1
Pastepal version 2.16.7

**Comment by onmyway133** [comment]
@Chelayel hi thanks for the feedback. For now PastePal only performs the history cleanup when it starts only, not periodically every day

**Comment by Chelayel** [comment]
@onmyway133 thank you for the info
